### PR TITLE
Add django-nap

### PR DESCRIPTION
**Pull request by jpic**
It looks like django-adapters will really want this feature.

This comfirms the existence of a data change step - which is exactly the kind of thing we're going to want to be able to recreate client side, i was thinking perhaps with a channel server push adapter...

### CODE REVIEW

**Comment by funkybob** [comment]
Aww, you're gonna make me blush! :)

**Comment by jpic** [comment]
@funkybob your app is so beautiful how can we miss it, i'm glad you're onboard !
Have you ever tried to extract your mapping system from django-nap and make it generic ?

**Comment by funkybob** [comment]
You can already, if you skip the ModelMapper code

On 12 March 2018 01:13:35 GMT+11:00, "∞" <notifications@github.com> wrote:
>@funkybob your app is so beautiful how can we miss it, i'm glad you're
>onboard !
>Have you ever tried to extract your mapping system from django-nap and
>make it generic ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mjtamlyn/django-adapters/pull/42#issuecomment-372118574

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by funkybob** [comment]
Another [much simpler] one you might consider looking at is https://github.com/funkybob/verity

**Comment by jpic** [comment]
Nice piece of work, absolutely reusable imho :1st_place_medal:

**Comment by jpic** [comment]
Do think django-adapters should make it so that verity needs to just add an adapter, so projects can reuse adapters from different apps and interchange them ? :thinking:

**Comment by mjtamlyn** [comment]
Thanks, definitely a package to have on the list as inspiration!

**Pull request merged**
